### ISSUE TITLE
Hash sum mismatch when attempting to install Microsoft ODBC Driver on Debian

### ISSUE THREAD

**Issue by yfayed** [microsoft/linux-package-repositories#175]
**Describe the issue**
When attempting to install the Microsoft ODBC Driver on Debian Container image Fails to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-all/Packages.gz  Hash Sum mismatch

**When did the issue occur?**
17-SEP-2024 11:07:05 UTC

**If applicable, what package did you attempt to install, and from which repo?**
`https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-all/Packages.gz`

**Steps to Reproduce**
```
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
```

**Actual Result**
```
Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-all/Packages.gz  Hash Sum mismatch
5.501    Hashes of expected file:
5.501     - Filesize:2625 [weak]
5.501     - SHA512:b1182c78404f85c62022af7f5ba210be0369d4f2fd5afa1c48702bfa01210cc0e9ae79511d911e82fa3ff3e4ec61daa8fa2f4cb5786899eeac38884d45558e19
5.501     - SHA256:e77e30326a4bbe8783b6706a1b838cc8adb43fb84576bdd2504f0be90d92a507
5.501    Hashes of received file:
5.501     - SHA512:1a0e0917f03cbb522a7650131141e032d9792696f5bb44a8da3ecdf49ca6ba878f1d61771643d4af1027a55f03a213f90ed467b5c23fbeddd9aa398d70bba345
5.501     - SHA256:459890d51924baa6dc6d053087f0c8948c7f5b200e3bcebf34ea5622e065f2ea
5.501     - Filesize:2625 [weak]
5.501    Last modification reported: Tue, 17 Sep 2024 08:35:28 +0000
5.501    Release file created at: Thu, 12 Sep 2024 18:16:57 +0000
```

**Expected Result**
Hashes should match and the install script should execute without issue

**Additional Info**
Based in Egypt, Tried to run it in Egypt as well as trying to run in a VM based in US-East2

**Comment by acheng-01** [comment]
Hi @yfayed, thank you for filing this issue. I believe the issues you are experiencing are also discussed in #174. In short there are a few things going on:

- Debian metadata can temporarily go out of sync when the repo is published. For this issue, you can check to see if your client supports pulling from by-hash files. We are also planning on implementing a change tomorrow to shorten the TTL on these files so that that out-of-sync window shrinks.
- There might be an issue happening with our CDN provider. We have already notified them to investigate.

Please continue this discussion on #174 as I am closing this issue as related to that one, thanks!
