### ISSUE TITLE
MDATP Package Missing from Amazon Linux

### ISSUE THREAD

**Issue by x3nc0n** [microsoft/linux-package-repositories#178]
**Describe the issue**
mdatp packages were removed from the Amazon Linux 2 repo
**When did the issue occur?**
Noticed it today, not sure when it started
Last update was:  26-Aug-2024 09:33

**If applicable, what package did you attempt to install, and from which repo?**

mdatp from https://packages.microsoft.com/amazonlinux/2/prod/ or insiders-fast or insiders-slow

**Steps to Reproduce**
On a machine with the Microsoft repo configured, run `sudo yum install mdatp`

**Actual Result**
No package mdatp available.
Error: Nothing to do

**Expected Result**

mdatp installs

**Screenshots**
![image](https://github.com/user-attachments/assets/bc4e4c8d-1ac9-491d-acb6-b45190c162da)
**Additional context**

**Comment by acheng-01** [comment]
Hi @x3nc0n, thank you for opening this issue. Please check https://github.com/microsoft/mdatp-xplat/issues for any existing issues regarding this or otherwise open a new one. We PMC are only responsible for hosting these packages and are not responsible for the packages themselves.

I am closing this issue as not actionable from our end.

**Comment by mbearup** [comment]
[like]  Matt Bearup reacted to your message:
________________________________
