### ISSUE TITLE
Will Moby Packages remain in the repository?

### ISSUE THREAD

**Issue by marcogracklauer** [microsoft/linux-package-repositories#197]
We are currently experimenting with moby packages on a Red Hat Enterprise Linux. Since we are using Defender, we have already set up the linux-package-repositorys in our environment. We were surprised to see moby included in this repository as it is not a native Microsoft product. 

Can we assume that the moby packages will remain in this repository in the long term?

Thank you very much!

**Comment by marcogracklauer** [comment]
Here you are :)
https://packages.microsoft.com/rhel/9/prod/Packages/m/

**Comment by Klaas-** [comment]
If I remember correctly they are there for some azure IOT stuff, I complained about them being in here in past to support, but best they could do is not update docker-ce installs with their packages ;)

**Comment by Klaas-** [comment]
https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.5 I think that was it :) so from my understanding that's the usecase that MSFT supports with those packages, not as a general container engine. Also they are behind with their releases example 27.3.1 MSFT release 05-Dec-2024, moby/docker-ce release 20-Sep-2024

**Comment by mbearup** [comment]
@marcogracklauer,
- To answer your primary question, yes, these packages will remain in this repo (and continue to be published to this repo) for the foreseeable future, barring some compelling reason to revisit that plan.
- As to the implied question (why are these packages present), it's because various teams requested that they be made available. Moby packages are also published to the Debian and Ubuntu repos.

Regarding the update cadence, there is automation to build moby packages as releases are cut, but a change in the upstream branching strategy has forced the team to revisit that automation.

For reference, this repo (linux-package-repositories) is primarily for the infrastructure supporting packages.microsoft.com (timeouts, checksum mismatches, etc). Questions regarding the moby packages can be directly to **github.com/Azure/moby-packaging**

**Comment by marcogracklauer** [comment]
@mbearup thank you very much for your clear statement and answer. We will continue to start our tests with Moby Packages 👍🏻
