### ISSUE TITLE
Ubuntu 22.04 LTS Repository Not Working

### ISSUE THREAD

**Issue by aconstantinides** [microsoft/linux-package-repositories#24]
Performing  a 
`sudo apt-get update`

after adding repository to Ubuntu

The following error is produced

The repository 'https://packages.microsoft.com/ubuntu/22.04/mssql-server-2022 jammy Release' does not have a Release file.

The same for 20.04 release is working folder structure of 22.04 is not the same with 20.04

**Comment by mbearup** [comment]
The release file for ubuntu 22.04 is empty because no MSSQL packages have yet been published for that distribution.
Regarding 20.04. I see release files for [mssql server 2022](https://packages.microsoft.com/ubuntu/20.04/mssql-server-2022/dists/focal/) and [2019](https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019/dists/focal/). Could you clarify what issue you experience with 20.04?

**Comment by aconstantinides** [comment]
Ok got it. 20.04 release is working fine.
