### ISSUE TITLE
Error downloading a package for Debian 12 from packages.microsoft.com (repo not signed)

### ISSUE THREAD

**Issue by qtdyj** [microsoft/linux-package-repositories#75]
**Describe the issue**
Error downloading package for Debian 12 from packages.microsoft.com.  I would like assistance to help understand what the root cause is.

**When did the issue occur?**
Issue was brought to my attention on 8/9/23.

**If applicable, what package did you attempt to install, and from which repo?**
Package: azcmagent

**Steps to Reproduce**
>> sudo -E apt update
<img width="441" alt="image" src="https://github.com/microsoft/linux-package-repositories/assets/103778477/3106f984-1390-4402-a079-8e52eeaa9768">

>> curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
<img width="376" alt="image" src="https://github.com/microsoft/linux-package-repositories/assets/103778477/145edd12-db96-4a1f-91f2-0fcc5d0b6257">

>> curl -sSL https://packages.microsoft.com/config/debian/12/prod.list | sudo tee /etc/apt/sources.list.d/microsoft-prod.list
<img width="441" alt="image" src="https://github.com/microsoft/linux-package-repositories/assets/103778477/5962691a-ca7d-4be8-adce-5c8b1d6250dd">

>> sudo -E apt-get update
<img width="438" alt="image" src="https://github.com/microsoft/linux-package-repositories/assets/103778477/ba04a834-cf35-4dee-81d6-5ab96f7d38ec">

>> sudo -E apt install -y azcmagent
<img width="137" alt="image" src="https://github.com/microsoft/linux-package-repositories/assets/103778477/b60051bf-fea6-478a-826b-45ad44923861">

**Actual Result**
See screenshots in the repro steps.

**Expected Result**
Package downloaded successfully.

Below is the output from the same steps done on Debian 11:
<img width="327" alt="image" src="https://github.com/microsoft/linux-package-repositories/assets/103778477/4d046329-89a5-43c8-b7ad-b1f32458e15b">

<img width="339" alt="image" src="https://github.com/microsoft/linux-package-repositories/assets/103778477/b041c412-cdbb-412c-b422-a2732ada0e9b">

<img width="402" alt="image" src="https://github.com/microsoft/linux-package-repositories/assets/103778477/5ebc7946-10bf-4f13-9d99-8ded72e664bb">

**Comment by mbearup** [comment]
@qtdyj ,
The repos are signed with the BE1229CF pubkey, and per the screenshots, it doesn't look like this key ins installed where it needs to be.
- Per your second screenshot, apt-key is deprecated. This is because it downloads the specified key into `/etc/apt/trusted.gpg.d`, which is reserved for OS keys (not third party/PPA keys such as ours).
- The "new" guidance is for 3P/PPA repos to use the `signed-by` directive, so that apt knows where to find the associated signing key.
- Per the screenshot, we can see that this .list file expects its signing key to be in `/usr/share/keyrings`.
- The fix is to download/dearmor the pubkey and write it into the `/usr/share/keyrings` folder, and the following commands will do that. 
`curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg`
Note that the deprecation of `apt-key` and the change of scope for `/etc/apt/trusted.gpg.d` are not things that we control. These are OSS/distro policies, and we simply aim to align with them (via the `signed-by` directive). We're exploring options to simplify repo onboarding in the future.

**Comment by sdherr** [comment]
I'll add that [this process](https://learn.microsoft.com/en-us/linux/packages#debian-based-linux-distributions) should work properly.
