### ISSUE TITLE
What is the correct method to set up a repo mirror for PMC?

### ISSUE THREAD

**Issue by KernelTom-MS** [microsoft/linux-package-repositories#79]
**Describe the issue**
Need to allow systems without internet access to access package repository. Would like to use a local mirror. What is the correct method to set up a pkg repo mirror for PMC?
 
**When did the issue occur?**
Now

**If applicable, what package did you attempt to install, and from which repo?**
trying to install azure-cli for ubuntu

**Steps to Reproduce**
n/a

**Actual Result**
Cannot directly access PMC

**Expected Result**
Either have a local mirror or proxy access to PMC (local mirror preferred)

**Screenshots**
n/a
**Additional context**
n/a

**Comment by Klaas-** [comment]
I am guessing you can use a wide range of tools for this, the most obvious would be https://pulpproject.org/ because that is backing packages.microsoft.com but there are other tools stuff like https://jfrog.com/artifactory/ or https://www.sonatype.com/products/sonatype-nexus-repository -- or you can even mirror it on cli https://help.ubuntu.com/community/AptGet/Offline/Repository/

**Comment by daviddavis** [comment]
There's no official way to mirror a PMC repo locally but @Klaas- gave some good options.
